format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
$nix_shell\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
$hostname\

"""

# Enables the blank line at the start of the prompt
 add_newline = true

# ~/.config/starship.toml

[hostname]
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = ''
disabled = false


[nix_shell]
disabled = false
symbol = '❄️'
pure_msg = 'pure'
impure_msg = 'impure'
unknown_msg = 'unknown'
format = '[$symbol nix-shell]($style)'
style = "fg:black bg:#06969A"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:black bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "fg:black bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 20
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "   "
pyenv_version_name = true
pyenv_prefix = " "
style = "fg:black bg:#86BBD8"
format = "[$symbol$pyenv_prefix$version]($style)"


[docker_context]
symbol = " "
style = "fg:black bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:black bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:black bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:black bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "fg:black bg:#33658A"
format = '[ ♥ $time ]($style)'
